apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor-skrypt
  namespace: my-monitoring
spec:
  schedule: "*/5 * * * *"  # Co 5 minut
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: monitor
            image: ghcr.io/kt-tech-01/moj-monitor:v2
          restartPolicy: OnFailure
